
# a = Photo.create(location: 1, note_id: Note.first.id)
# Photo.last.picture.attach(io: File.open('/Users/lifazul/Desktop/sample.jpg'), filename: 'sample.jpg')

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
  region: <%= Rails.application.credentials.aws[:region] %>
  bucket: <%= Rails.application.credentials.aws[:bucket] %>
